flowchart LR
  RechnSB{"Rechnungssumme Brutto"}
  RechnSB -- "kleiner 250€" --> Kleinbetragsrechnung
  subgraph Rechnungsangaben
    subgraph Kleinbetragsrechnung
      NAn("✔️ Name und Anschrift \n des leistenden Unternehmers")
      AustD("✔️ Austellungsdatum")
      MengeBz("✔️ Menge und Bezeichnung \n des Gegenstands")
      ProzUst("✔️ Prozentsatz der angewandten USt")
    end
    SteurNr("✔️ Steuernummer oder USt-ID")
    RechNr("✔️ Fortlaufende Rechnungsnummer")
    LieferDat("✔️ Liefer- \n und Leistungszeitraum")
    Netto("✔️ Netto- \n und Steuerbetrag")
  end
